# DeathDropControl Configuration
# Docs: https://github.com/RainwoodL/DeathDropControl/wiki

# Global switch (true=on/false=off)
enable: true

# Enabled worlds (Only process deaths in these worlds)
# Use exact world names from /worlds command
worlds:
  - world
  - world_nether
  - world_the_end

# Protected slots (Items in these slots won't drop)
# Slot Guide:
#   0-8   : Hotbar
#   9-35  : Inventory
#   36-39 : Armor slots
#   40    : Off-hand
protected-slots:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8

# Death message settings
broadcast:
  # Enable death announcements
  enable: false

  # Message template (Use %player% for name)
  message: '%player% was slain by the world'